### ISSUE TITLE
Memory usage improvement

### ISSUE THREAD

**Issue by EmiOnGit** [EmiOnGit/warbler_grass#27]
Currently, there are a couple of places where memory is wasted.
Problems I've noticed:
1)  A user cannot reuse `Grass` without copying the internal data.
It is  not unthinkable that a user might want to spawn the same grass at different locations.
Currently this would result in a big waste of memory since the internal grass data can be quite big.
2) The `Grass` data will completely copied to the render world.
Actually, we never use the data in the render world beside creating the buffer once. We shouldn't copy the grass data to the render world to begin with
3) If an Grass entity gets cached once in the renderworld, the caches  are never freed, even if the entity itself are despawned
4) We are currently saving the position of each grass blade independently.
This might seem obvious but is avoidable. In a dense grass field we should be able interpolate at least the height of most blades. 
5) Since we only use the cached `Buffer`s to create a cached `Bindgroup` and we could as well remove the cached buffers
As I see it currently, it is useless to cache the buffers since they'd have to be recalculated every time when they are used.

6) I'm sure there are more so this list might grow 
 
## Describe the solution you'd like
This issue is meant as a overview. I'd open a issue for the separated problems as there is not a solution to solve them all at once.
However, it seems to be a good idea to reimplement the `Grass` component as an `Asset`, similar to the `Mesh` asset.
The grass entities then can hold the grass asset handle.
This offers a couple benefits: 
- Entities could just clone the asset handle (problem 1)
- We could free the caches if the corresponding grass asset doesn't have any handles that are strong (problem 3)
- Since bevy tracks if assets change we can use that instead of our own implementation to check for changes

**Comment by EmiOnGit** [comment]
Also importend on this topic is that if we decide to load the positions of the blades dynamically as in #9 and #8 we would lose the need for storing the blade positions in `Grass` completely.

**Comment by janhohenheim** [comment]
Wait what, you managed to fix all of this? 😮 
Or did you close the issue to split it into other issues?

**Comment by EmiOnGit** [comment]
Well most of them are fixed or mostly fixed.
1) With the implementation of density maps, users can reuse the data by simply cloning the handles to their images.
This already works for height maps
2) I noticed that we actually have to copy it once because we can not create any buffers on main world.
However, the buffer wouldn't be cheaper to copy than the grass anyway.
After the bindgroup is created the grass get's deleted in the render world however. 
3) Still not fixed
4) Fixed by using height maps + density maps
5) Fixed this. No Buffers are stored anymore

**Comment by EmiOnGit** [comment]
Some of the things listed are only implemented in the performance branch. (depends on bevy_0.10 branch so can't be merged right now)

**Comment by janhohenheim** [comment]
Aah I see. I just saw your comment regarding performance gains, that's hella nice 😄

**Comment by EmiOnGit** [comment]
I'm really optimistic for #9 a 2x improvement from the current performance might be doable :D (we'll see)
