### ISSUE TITLE
Grass editor for height maps

### ISSUE THREAD

**Issue by EmiOnGit** [EmiOnGit/warbler_grass#36]
## What problem does this solve or what need does it fill?
Currently, it is rather hard to create grass using height maps.
Even though the height maps are dynamically updated every time the file change there should be a tool to change them in a bevy directly

## Describe the solution you'd like
A plugin which let you change the height of marked height maps. 
It should be possible to lower and raise parts of the grass and if wanted the new height map should be writeable to disk if wanted.
The tools provided should be kept rather simple to keep the scope tiny enough.

This tool should later be able to also draw on density maps as they are implemented

## Describe what is for debate
The big question is if this should be split into a separate crate since it "bloats" this crate with functionality not needed for most people.

**Comment by janhohenheim** [comment]
No bloat necessary, you can just hide the editor behind a feature 😉

**Comment by EmiOnGit** [comment]
Mh, this is true :D

**Comment by EmiOnGit** [comment]
I actually already started implementing this a bit.

https://user-images.githubusercontent.com/95967983/222784730-810ec486-8982-495e-b360-984fbf6c7cf6.mp4

**Comment by EmiOnGit** [comment]
Yes, I did admire that already :D 
I think it would be useful to make that possible from the crate.
There are also algorithms to generate height maps from meshes. 
This would be really useful for a lot of people as the ground is often a mesh

**Comment by EmiOnGit** [comment]
The editor is forming but still some way to go.

https://user-images.githubusercontent.com/95967983/222926835-96f6c7ca-d40e-4945-ae31-3dbcd0f1551b.mp4
