### ISSUE TITLE
grass doesn't show up anymore with `WarblersExplicitBundle`

### ISSUE THREAD

**Issue by EmiOnGit** [EmiOnGit/warbler_grass#52]
I've updated to 0.3 and changed my spawning code to use the `WarblersExplicitBundle`, since that seemed like the closest thing to my existing grass generation code. However, now my grass doesn't show up anymore 😱 
Code: https://github.com/janhohenheim/foxtrot/pull/228/files#diff-f7cf21045cf163dc0a11d0ebf9b1d7541c14da67855b984f66147b482cbfeed9L48-L66
![image](https://user-images.githubusercontent.com/9047632/225042501-9341f92f-a381-482b-a1db-e59ca12e03fd.png)
Looking at the generated positions, they seem valid to me:
![image](https://user-images.githubusercontent.com/9047632/225042709-5a6040c5-3258-48d4-8565-5542a6013d6d.png)

Any idea on what I might be doing wrong? Does this have something to do with the grass not being visible from the start and thus somehow not entering a cache?

_Originally posted by @janhohenheim in https://github.com/EmiOnGit/warbler_grass/discussions/47#discussioncomment-5308728_

**Comment by EmiOnGit** [comment]
Alright it seems it was no visible because you ran the spawn in `PostUpdate` resulting in the `Aabb` added by bevy and not by `warblers_grass`.
Therefore the grass was invisible thanks to the frustum culling.
I pushed the fix to the main branch. Can you test if everything works for you on main?

**Comment by janhohenheim** [comment]
Cool, thanks for reacting so quickly! Will check when I'm home.

**Comment by janhohenheim** [comment]
Works like a charm, thanks again!
I love the new logo btw, looks very friendly 😄

**Comment by EmiOnGit** [comment]
Ah don't worry, actually I'm almost happy about feedback.
It's hard to write something without knowing how it works

Thanks I wanted to try my art skills :D
