### ISSUE TITLE
Replacement for explicit bundle

### ISSUE THREAD

**Issue by janhohenheim** [EmiOnGit/warbler_grass#71]
I'm finally coming around to updating foxtrot to Bevy 0.12 and am updating all dependencies in the process. I noticed you removed the explicit bundle telling warbler grass where to place grass. What's the recommended alternative? Using a height map?

**Comment by EmiOnGit** [comment]
Yes!
A height map in combination with a density map work way better than the system we had before anyway.
After updating to bevy 0.12 I can make a pr for you. 
I'm excited to see that you intend to update Foxtrot! :)

**Comment by janhohenheim** [comment]
Thanks a bunch :)
