### ISSUE TITLE
Shader crash: mesh_view_layout_multisampled_depth

### ISSUE THREAD

**Issue by ethereumdegen** [EmiOnGit/warbler_grass#84]
## Describe the bug
 

Caused by:
    In a RenderPass
      note: encoder = `main_opaque_pass_3d_command_encoder`
    In a draw command, indexed:true indirect:false
      note: render pipeline = `Grass Render Pipeline`
    Incompatible bind group at index 0 in the current render pipeline
      note: Should be compatible an with an explicit bind group layout with label = `mesh_view_layout`
      note: Assigned explicit bind group layout with label = `mesh_view_layout_multisampled_depth`
      note: Entry 20 not found in expected bind group layout

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

 

## To Reproduce
 Attach the '  DepthPrepass' component to the bevy  camera 

## Expected behavior
 shouldnt panic ?  
 

## Additional context
the engine panics ! not sure why .    This may be more of a bevy and wpgu thing that needs to be investigated more

**Comment by EmiOnGit** [comment]
Looks nasty. I'll have to take a look at the problem a bit more in depth but it might also be problem on my end

**Comment by ethereumdegen** [comment]
Thanks . I need depth prepass bc i use it in a different shader .. my bevy magic fx crate uses it to make certain vfx have a hacked depth value so i can make vfx look behind things even if they arent actually spatially behind them .  So i can make things glow super saiyan (fire behind model)  and such

**Comment by EmiOnGit** [comment]
The linked PR should fix the crashes. However, the grass itself will not be rendered to any prepass texture. (See pr desc.).
