### ISSUE TITLE
Loading grass from density map

### ISSUE THREAD

**Issue by EmiOnGit** [EmiOnGit/warbler_grass#9]
## What problem does this solve or what need does it fill?
Currently the only proper way to initialize grass is to explicitly create each grass blade individually.
This is obviously unsustainable for a game.
It may be desirable to let an advanced user create his own pipeline for providing the grass blades, however it makes the crate not accessible for many others.
The approach I suggest is using density maps in combination with height maps.
Since the pipeline of generating the grass blades, there are multiple issues for separate parts.
This is about the calculation of the xz-world positions of the grass.

**IMPORTEND NOTE**
With height of grass blades in this issue I always refer to the y-position of the blade in worldspace!
Not the height of the grass blade itself.

## Describe the solution you'd like
A very nice way to approach this would be to use density maps.
Density maps are grayscale images which indicate a more "dense" area by being darker.

Multiple ways to calculate the explicit positions of a density map exist, but I propose [dithering](https://en.wikipedia.org/wiki/Dither) of the density map with a slight application of noise.

An aabb box could then be used to scale along the xz axis. (Which would be needed in [this feature](https://github.com/EmiOnGit/warblersneeds/issues/8) anyway.

## Describe what is for debate
If the pipeline could be transformed to read the positions directly from the dithered density map,
it should be possible to create new grass at runtime cheaply. It would even open a opportunity to implementing something like a "grass brush" used like in the unity/UE engine (This would be awesome!)
This would how ever mean that we would limit this crate mostly to using this technique

**Comment by EmiOnGit** [comment]
Loading from density map is going forward.
The math is still not figured out but the loading seem to work.
You can see a field of  around 26 million grass blades running at around 200 fps.
I think these numbers are insane :D

https://user-images.githubusercontent.com/95967983/222864253-b97c6b9f-4cbd-44e4-a7d3-40130b87f913.mp4

**Comment by janhohenheim** [comment]
Daaaamn that's insane! You should definitely put these numbers in the readme after the merge 😄
